### ISSUE TITLE
How to use the code

### ISSUE THREAD

**Issue by alecive** [themichaeltsang/clm_catkin-indigo#2]
@themichaeltsang I managed to compile the code, doing what I said in #1 (on this topic, I will open a pull request with a better `README.md` and all the modifications I made to streamline the `CMake`). Now that it compiles, I do not know how to make it work. What Should I do?

If I run it, this is the result:

```
(~/code/catkin_my_ws) () 
[alecive@malakim]$ ./devel/lib/clm_bridge/clm_bridge 
Could not find the landmark detection model to load
Could not find triangulation files, exiting.
```

Where do I find the triangulation files (i.e. `"model/tris_68_full.txt"`), and later on the AU predictors (i.e. `"AU_predictors/AU_all_best.txt"`)?

**Comment by themichaeltsang** [comment]
Hi @alecive,

Are they possibly in the \bin folder? If not, let me know.

-Michael

**Comment by alecive** [comment]
I found the files in `lib/local/CLM/model` and `lib/local/FaceAnalyser/AUPRedictor`. How can I tell the executable where these files are?

Also, what else should I do in order for the bridge to work? Do I simply have to run `roslaunch clm_bridge clm_bridge.launch`?

**Comment by alecive** [comment]
@themichaeltsang the executable accepts a big set of parameters and I don't know what to do with them.

**Comment by alecive** [comment]
Also, how can I load the landmark detection model? It does not belong to `clm_bridge.cpp`, but directly to the library.

**Comment by themichaeltsang** [comment]
@alecive 
try putting the files in /devel/lib/clm_bridge/
Then roslaunch as you wrote. You should not have to input parameters, unless the webcam isn't detected

**Comment by alecive** [comment]
Ok, this works. I will modify the CMAke to do that automatically so that we don't have to do it manually any more. Thank you!
